Repository ncihtan/htan-portal, pull requests merged in 2024-11, with the labels that each got.

#700 Fix empty Manifest Names column download content
  components/DataSchema.tsx
Labels: bug

#699 Update "Download selected files" modal
  packages/data-portal-explore/src/components/DataAvailabilityTable.tsx
  packages/data-portal-explore/src/components/FileFilterControls.tsx
  packages/data-portal-explore/src/components/FileTable.tsx
Labels: enhancement

#712 Remove policy documents
  pages/static/resources.html
Labels: documentation

#697 Add newsletter link
  components/HtanNavbar.tsx
Labels: enhancement
