Repository ncihtan/htan-portal, pull requests merged in 2024-04, with the labels that each got.

#612 Show Coming Soon message for only imaging level 2 files
  packages/data-portal-explore/src/components/FileTable.tsx
Labels: enhancement

#617 add more coarse filter for organ type on the explore page
  packages/data-portal-commons/src/lib/getCaseValues.ts
  packages/data-portal-commons/src/lib/types.ts
  packages/data-portal-explore/src/components/FileFilterControls.tsx
  packages/data-portal-utils/src/lib/types.ts
Labels: enhancement, gsoc

#624 Include coming soon in the not downloadable files list
  packages/data-portal-explore/src/components/FileTable.tsx
Labels: bug

#602 🐛 Bug Fix: Show Less Button Incorrect Rendering
  packages/data-portal-commons/src/components/ExpandableText.tsx
Labels: gsoc

#631 Fix an infinite loop issue with findAllAncestors
  packages/data-portal-schema/src/lib/dataSchemaHelpers.ts
Labels: bug
